export const INIT_BLOGS = 'INIT_BLOGS'
export const LIKE_BLOG = 'LIKE_BLOG'
export const NEW_BLOG = 'NEW_BLOG'
export const DELETE_BLOG = 'DELETE_BLOG'
export const COMMENT_BLOG = 'COMMENT_BLOG'

export const GET_USERS = 'GET_USERS'

export const LOGIN_APP = 'LOGIN_APP'
export const LOGOUT_APP = 'LOGOUT_APP'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
